### ISSUE TITLE
Consider change default for flyway locations from classpath:db/migration to filesystem:db/migration

### ISSUE THREAD

**Issue by romchellis** [testcontainers/testcontainers-jooq-codegen-maven-plugin#15]
In order to avoid  provision explicitly flyway locations like this
``` xml
                            <flyway>
                                <locations>
                                    filesystem:src/main/resources/db/migration
                                </locations>
                            </flyway>
```  
We can add default as it implemented in `flyway-maven-plugin`

```java
locations = new String[] {
                        Location.FILESYSTEM_PREFIX + workDir.getAbsolutePath() + "/src/main/resources/db/migration"
                };
```

**Comment by simasch** [comment]
Why not use the classpath? 

https://flywaydb.org/documentation/configuration/parameters/locations

**Comment by romchellis** [comment]
Hi @simasch 
Now if locations were not provided, `classpath:db/migration` default will be set.So since it is maven plugin, by default target directory does not include resources at `generate` stage, so these resources will not be used by flyway.

**Comment by simasch** [comment]
@romchellis Ah you right!
