### ISSUE TITLE
Scope of most dependencies should be optional

### ISSUE THREAD

**Issue by simasch** [testcontainers/testcontainers-jooq-codegen-maven-plugin#21]
I just noticed that most of the dependencies have default scope, and a build will download JDBC drivers, Liquibase etc. even if they are not used!

What do you think to make non mandatory and the user has to those if needed?

**Comment by romchellis** [comment]
Since it is maven plugin they will be not included to final jar

**Comment by romchellis** [comment]
Hi @simasch, what are your thoughts on the comment above?
In fact, it is not possible to conditionally load dependencies depending on plugin properties.
Furthermore, they don't pollute the target jar; plugin dependencies are safe for the caller's project.
Should we close the issue?

**Comment by simasch** [comment]
Hi @romchellis 
Sure 😅
It looks like I was a bit confused when writing this issue. Sorry about that.

**Comment by romchellis** [comment]
> Hi @romchellis Sure 😅 It looks like I was a bit confused when writing this issue. Sorry about that.

No worries, I was not a familiar with maven plugins that deep before as well until I took this project :)

**Comment by simasch** [comment]
The thing is that I maintain a Maven plugin myself and should be well aware of that (shame on me).
