### ISSUE TITLE
Postgis

### ISSUE THREAD

**Issue by ekeraghossian** [testcontainers/testcontainers-jooq-codegen-maven-plugin#24]
Hi, 
I need to use this plugin with a postgis database, is there any easy way to achieve that since it is a flavour of postgres? 

I made some changes to include postgis in the database type and create a container. But it is failing to pull the postgis image from the container that runs testcontainers.

Regards,
Eskandar

**Comment by romchellis** [comment]
Hi @ekeraghossian , could you create a pull request for MWE? I would see and try to help

**Comment by zzzLobster** [comment]
Hi @romchellis , I have created a PR for this issue.
I thought about making more strict, like to enable Postgis specifically, but finally decided that it is also good to have ability to use any custom image.

**Comment by romchellis** [comment]
hi @zzzLobster  ,seems ok
