### ISSUE TITLE
DockerImageName customization feature version 0.0.4

### ISSUE THREAD

**Issue by ManishAnandProgrammer** [testcontainers/testcontainers-jooq-codegen-maven-plugin#38]
Need to configure docker-image name like below::

DockerImageName.parse("mdillon/postgis:latest").asCompatibleSubstituteFor("postgres")

**Comment by rajadilipkolli** [comment]
#24  should have fixed it, can you try with latest version

**Comment by timbuethe** [comment]
If I get this correctly, it should be fixed in 0.0.4, but that is not released yet. Any plans to release a new version anytime soon?

**Comment by eddumelendez** [comment]
Version 0.0.4 has been released. See https://repo1.maven.org/maven2/org/testcontainers/testcontainers-jooq-codegen-maven-plugin/0.0.4/
