### ISSUE TITLE
0.0.2 Release

### ISSUE THREAD

**Issue by romchellis** [testcontainers/testcontainers-jooq-codegen-maven-plugin#8]
Hi @sivaprasadreddy 
Would you mind releasing 0.0.2 ?

**Comment by sivaprasadreddy** [comment]
@romchellis I am thinking of addressing https://github.com/testcontainers/jooq-testcontainers-codegen-maven-plugin/issues/4 before 0.0.2 release. It's not a blocker, but I think it's better to have automated test ASAP.

**Comment by sivaprasadreddy** [comment]
Version 0.0.2 is released.

Thanks @romchellis for contributing the major features/changes in this release.
